### ISSUE TITLE
Disable password auth when using an SSH key

### ISSUE THREAD

**Issue by jonc125** [UCL-CloudLabs/deployer#17]
Currently the template always has:

`disable_password_authentication = false`

**Comment by raquelalegre** [comment]
Yes, there's some hardcoded things that'll have to be modified depending on user input. I will make a new issue with those and include this. There are some in #16 as well.

**Comment by jonc125** [comment]
This should be fixed by https://github.com/UCL-CloudLabs/user-portal/pull/18, though we should probably test to verify that!

**Comment by jonc125** [comment]
Just checked - it does disallow password login, so can close.
